export const EVENTS = {
  SETTINGS: 'settings:updated',
  SLIDES: 'slides:updated',
  STATS: 'stats:updated',
  SECTIONS: 'sections:updated',
  SERVICES: 'services:updated',
  PROJECTS: 'projects:updated',
  PROJECT_CATEGORIES: 'projectcategories:updated',
  PACKAGES: 'packages:updated',
  POSTS: 'posts:updated',
  POST_CATEGORIES: 'postcategories:updated',
  TAGS: 'tags:updated',
  COMMENTS: 'comments:updated',
  PARTNERS: 'partners:updated',
  TESTIMONIALS: 'testimonials:updated',
  TEAM: 'team:updated',
  TIMELINE: 'timeline:updated',
  CERTIFICATES: 'certificates:updated',
  JOBS: 'jobs:updated',
  APPLICATIONS: 'applications:updated',
  MESSAGES: 'messages:updated',
  QUOTES: 'quotes:updated',
  PACKAGE_REQUESTS: 'packagerequests:updated',
  FAQ: 'faq:updated',
  MENUS: 'menus:updated',
  BANNERS: 'banners:updated',
  PAGES: 'pages:updated',
  USERS: 'users:updated',
  ROLES: 'roles:updated',
  ANY: 'content:changed',
};

export default EVENTS;
